version: '3.8'

services:
  web:
    build: ./
    command: python app.py run -h 0.0.0.0
    ports:
      - 5000:8080
    environment:
      - FLASK_APP=junkfood
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://junkfood:junkfood:5432/junkfood      
    env_file:
      - ./.env.dev
    volumes: 
      - /junkfood-data:/usr/src/app/junkfood/static/data:z
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=junkfood
      - POSTGRES_PASSWORD=junkfood
      - POSTGRES_DB=junkfood
    env_file:
      - ./.env.dev  
volumes:
  postgres_data:      