version: '3.8'

services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes: 
      - /junkfood-data:/usr/src/app/junkfood/static/data:z
  db:
    restart: always
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod 
volumes:
  postgres_data:      